// src/app/(main)/page.jsx
import ChapterList from "@/components/shared/chapter-list"
import Pagination from "@/components/shared/pagination"
import SkeletonKomik from "@/components/shared/skeleton-komik"
import { komikModel } from "@/lib/repo"
import { FireIcon } from "@heroicons/react/24/solid"
import { Suspense } from "react"

const Home = async ({ searchParams }) => {
	const csp = await searchParams
	const query = csp?.query || ""
	const currentPage = Number(csp?.page) || 1
	const data = await komikModel.getSearchPagin(query, currentPage)
	const totalPage = await komikModel.getPage(query)
	return (
		<>
			<div className="flex justify-center items-center gap-4">
				<FireIcon className="w-6 text-red-500" />
				<h1 className="text-2xl font-bold">Home</h1>
			</div>
			<div className="my-8 grid grid-cols-3 gap-4 md:grid-cols-6 md:gap-6">
				<Suspense key={query + currentPage} fallback={<SkeletonKomik />}>
					<ChapterList data={data} />
				</Suspense>
			</div>
			<div className="flex justify-center mt-4">
				<Pagination totalPages={totalPage} />
			</div>
		</>
	)
}

export default Home

// src/routes/(main)/+page.svelte
<script>
	import { page } from '$app/state';
	import ChapterList from '$lib/components/chapter-list.svelte';
	import FireIcon from '$lib/components/icons/fire_icon.svelte';
	import Pagination from '$lib/components/paginations/pagination.svelte';
	import SkeletonKomik from '$lib/components/skeletons/skeleton-komik.svelte';

	const { data } = $props();
	let search_query = $derived(page.url.searchParams.get('s') || '');
</script>

<svelte:head><title>ADK</title></svelte:head>
<div class="flex items-center justify-center gap-4">
	<FireIcon />
	<h1 class="text-2xl font-bold">Home</h1>
</div>
{#if search_query != ''}
	<p>Search result for: "{search_query}"</p>
{/if}
<div class="my-8 grid grid-cols-1 gap-4 md:grid-cols-6 md:gap-6">
	{#await data.komik}
		<SkeletonKomik />
	{:then komik}
		{#each komik as item (item.id)}
			<ChapterList data={item} pathName="" image_cdn={data.image_cdn} />
		{/each}
	{/await}
</div>
<div class="my-28 flex justify-center">
	<Pagination totalPages={data.totalPage} />
</div>
