// src/routes/(main)/tags/+page.svelte
<script lang="ts">
	import TagIcon from '$lib/components/icons/TagIcon.svelte';
	import SkeletonTags from '$lib/components/skeletons/skeleton-tags.svelte';
	import { type NewTags } from '$lib/server/db/queries/tags';
	import { capitalizeFirstLetter } from '$lib/utils';
	import { resolve } from '$app/paths';
	import Badge from '$lib/components/view/badge.svelte';

	interface TagsPageProps {
		dataTags: NewTags[];
	}

	const { data }: { data: TagsPageProps } = $props();
	let items = $derived.by(() => {
		const group = Object.groupBy(data.dataTags, (e) => e.type);
		const tags = [];
		for (const e in group) {
			tags.push({
				group: capitalizeFirstLetter(e),
				tags: group[e]
			});
		}
		return tags;
	});
</script>

<div class="flex items-center justify-center gap-4">
	<TagIcon />
	<h1 class="text-2xl font-bold">Tags</h1>
</div>
{#await data}
	<SkeletonTags />
	<!-- eslint-disable-next-line @typescript-eslint/no-unused-vars -->
{:then dataTags}
	{#each items as item, index (index)}
		<h2>{item.group}</h2>
		<div class="my-8 flex w-full flex-wrap items-center justify-center gap-2">
			{#each item.tags as tag, idx (idx)}
				<a href={resolve(`/tags/${tag.id}` as '/')} aria-label={tag.name}>
					<Badge text={tag.name} count={tag.count} />
				</a>
			{/each}
		</div>
	{/each}
{/await}

// src/app/(main)/tags/page.tsx
import { Skeleton } from "@/components/skeleton"
import { capitalizeFirstLetter, cn } from "@/lib/utils"
import { TagIcon } from "@heroicons/react/24/solid"
import Link from "next/link"
import { Suspense } from "react"
import type { Metadata } from 'next';
import { AllTags, getAllTags, groupTags, GroupTags, Tags } from "@/db/queries/tags"

export const revalidate = 3600;

export async function generateStaticParams() {
  const all: AllTags = await getAllTags()
  return all.map((item) => ({
    slug: item.id,
  }))
}

export const generateMetadata = (): Metadata => {
  return {
    title: 'Tags',
  }
}

const TagsPage = async () => {
  const data: AllTags = await getAllTags()
  return (
    <>
      <div className="flex justify-center items-center gap-4">
				<TagIcon className="w-6 text-red-500" />
				<h1 className="text-2xl font-bold">Tags</h1>
			</div>
      <Suspense key={data.length} fallback={<TagsSkeleton />}>
				<TagsElm data={data} />
			</Suspense>
    </>
  )
}


const TagsElm = ({ data }: {data:AllTags}) => {
  const items: GroupTags = groupTags(data)
  const tags = []
  for(const e in items){
    tags.push(<TagsRender key={e} title={capitalizeFirstLetter(e)} data={items[e] ?? []} />)
  }
  return (<>{tags.map((e) => e)}</>)
}

const TagsRender = ({ title, data }: {title:string, data:AllTags}) => {
  return (
		<>
			<h1>{title}</h1>
			<div className="my-8 flex gap-2 w-full flex-wrap justify-center items-center">
				{data.map((e: Tags) => (
					<Link href={`/tags/${e.id}`} key={e.id}>
						<div className="rounded bg-input px-4 py-1 cursor-pointer hover:bg-input/50">{e.name}</div>
					</Link>
				))}
			</div>
		</>
	)
}

const TagsSkeleton = () => {
  const data = [...Array(40).keys()]
	const width = ["px-12", "px-8", "px-10"]
  const generateTags = () => (data.map((e) => {
    const random = Math.floor(Math.random() * width.length)
    return <Skeleton key={e} className={cn(width[random], "rounded py-4")} />
  }))
  return (
		<>
			<div className="my-8 flex gap-2 w-full flex-wrap justify-center items-center">
				{generateTags().join("")}
			</div>
		</>
	)
}

export default TagsPage
