// src/components/chapter-list-online.tsx
import { CDNType, getCDN, getLanguage, NHMainPageType, ResultNHMainPageType } from "@/lib/nhapi";
import Link from "next/link";
import LazyImage from "./lazy-image";

const ChapterListOnline = async ({ data }: { data: NHMainPageType }) => {
	const pathname = `/online`;
	if (data.result.length === 0) {
		return (
			<>
				<div>
					<h4>Not Found!</h4>
				</div>
			</>
		);
	}
	const image_cdn: CDNType = await getCDN();
	const { thumb_servers } = image_cdn;
	return (
		<>
			<div className="my-8 grid grid-cols-2 gap-4 md:grid-cols-5 md:gap-6">
				{data.result.map((e, i) => {
					const cdn_thumb = thumb_servers[i % thumb_servers.length];
					const imgsrc = `${cdn_thumb}/${e.thumbnail}`;
					return <Card key={i} data={e} pathName={pathname} imgsrc={imgsrc} />;
				})}
			</div>
		</>
	);
};

type CardProps = {
	data: ResultNHMainPageType;
	pathName: string;
	imgsrc: string;
};

const Card: React.FC<CardProps> = ({ data, pathName, imgsrc }) => {
	const linkhref = `${pathName}/view/${data.id}`;
	const tagLanguage = getLanguage(data.tag_ids);
	const language = tagLanguage ? tagLanguage.flag : ``;
	return (
		<>
			<div className="linking group">
				<div className="relative h-[40vw] overflow-hidden rounded-xl md:h-[20vw]">
					<Link href={`${linkhref}`}>
						<LazyImage
							src={imgsrc}
							className="h-full w-full object-cover transition-all duration-200 ease-in-out group-hover:scale-125 group-hover:blur-sm"
						/>
						<div className="absolute right-2 bottom-2 bg-green-600 px-4 rounded">
							<p className="text-xs">{`${data.num_pages} Pages`}</p>
						</div>
					</Link>
				</div>
				<div className="relative">
					<div className="flex items-center justify-start truncate text-primary mt-1">
						<Link href={`${linkhref}`} aria-label={data.english_title}>
							<p className="text-md text-foreground">
								{language} {data.english_title}
							</p>
						</Link>
					</div>
					<div className="hidden group-hover:flex items-center justify-start text-primary mt-1 absolute left-0 top-0 bg-background z-50">
						<Link href={`${linkhref}`} aria-label={data.english_title}>
							<p className="text-md text-foreground">
								{language} {data.english_title}
							</p>
						</Link>
					</div>
				</div>
			</div>
		</>
	);
};

export default ChapterListOnline;

// src/lib/components/chapter-list-online.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import {
		getLanguage,
		type CDNType,
		type relatedType,
		type ResultNHMainPageType
	} from '$lib/nhapi';
	import { isMobile } from '$lib/utils';
	import LazyImage from './lazy-image.svelte';

	interface CardProps {
		data: ResultNHMainPageType | relatedType;
		pathName: string;
		image_cdn: CDNType;
		isResponsive?: boolean;
	}

	const { data, pathName, image_cdn, isResponsive = true }: CardProps = $props();
	let isMobi = $derived(isMobile() && isResponsive);
	let linkhref = $derived(`${pathName}/view/${data.id}`);
	const { thumb_servers } = $derived(image_cdn);
	const imgsrc = $derived.by(() => {
		let cdn_thumb = thumb_servers[Math.floor(Math.random() * thumb_servers.length)];
		return cdn_thumb + '/' + data.thumbnail;
	});
	let tagLanguage = $derived(getLanguage(data.tag_ids));
	let language = $derived(tagLanguage ? tagLanguage.flag : ``);
	$effect(() => {
		function handleResize() {
			isMobi = isMobile() && isResponsive;
		}

		window.addEventListener('resize', handleResize);
		return () => window.removeEventListener('resize', handleResize);
	});
</script>

{#if isMobi}
	<div class="linking group grid grid-cols-3 gap-2">
		<div class="relative h-[40vw] overflow-hidden rounded-xl md:h-[20vw]">
			<a href={resolve(`/${linkhref}` as `/`)} aria-label={`${data.id}`}>
				<LazyImage
					src={imgsrc}
					alt={data.media_id}
					className="h-full w-full object-cover transition-all duration-200 ease-in-out group-hover:scale-125 group-hover:blur-sm"
				/>
				<div class="absolute right-2 bottom-2 rounded bg-green-600 px-4">
					<p class="text-xs">{`${data.num_pages} Pages`}</p>
				</div>
			</a>
		</div>
		<div class="relative col-span-2">
			<div class="text-primary mt-1 flex items-center justify-start">
				<a href={resolve(`${linkhref}` as `/`)} aria-label={`${data.id}`}>
					<p class="text-sm font-semibold text-foreground">{language} {data.english_title}</p>
				</a>
			</div>
		</div>
	</div>
{:else}
	<div class="linking group">
		<div class="relative h-[40vw] overflow-hidden rounded-xl md:h-[20vw]">
			<a href={resolve(`/${linkhref}` as `/`)} aria-label={`${data.id}`}>
				<LazyImage
					src={imgsrc}
					alt={data.media_id}
					className="h-full w-full object-cover transition-all duration-200 ease-in-out group-hover:scale-125"
				/>
				<div class="absolute right-2 bottom-2 rounded bg-green-600 px-4">
					<p class="text-xs">{`${data.num_pages} Pages`}</p>
				</div>
			</a>
		</div>
		<div class="relative">
			<div class="text-primary mt-1 flex items-center justify-start truncate">
				<a href={resolve(`${linkhref}` as `/`)} aria-label={`${data.id}`}>
					<p class="text-md text-foreground">{language} {data.english_title}</p>
				</a>
			</div>
			<div
				class="text-primary absolute top-0 right-0 left-0 z-50 mt-1 hidden items-center justify-start rounded bg-border p-2 group-hover:flex"
			>
				<a href={resolve(`${linkhref}` as `/`)} aria-label={`${data.id}`}>
					<p class="text-md text-foreground">{language} {data.english_title}</p>
				</a>
			</div>
		</div>
	</div>
{/if}
