// src/components/shared/search.jsx
"use client"
import { MagnifyingGlassIcon, XMarkIcon } from "@heroicons/react/24/solid"
import { usePathname, useRouter, useSearchParams } from "next/navigation"
import { useDebouncedCallback } from "use-debounce"

const Search = () => {
	const searchParams = useSearchParams()
	const pathname = usePathname()
	const { replace } = useRouter()

	const handleSearch = useDebouncedCallback((term) => {
		const params = new URLSearchParams(searchParams)
		params.set("page", "1")
		if (term) {
			params.set("query", term)
		} else {
			params.delete("query")
		}
		replace(`${pathname}?${params.toString()}`)
	}, 300)

	return (
		<>
			<form className="flex bg-zinc-800 border border-zinc-700 text-white rounded-md shadow text-sm">
				<div aria-disabled="true" className="w-10 grid place-content-center">
					<MagnifyingGlassIcon className="w-4 h-4 text-white" />
				</div>
				<input
					type="text"
					spellCheck="false"
					name="text"
					className="bg-transparent py-1.5 outline-none placeholder:text-zinc-400 w-20 focus:w-48 transition-all"
					placeholder="Search..."
					onChange={(e) => handleSearch(e.target.value)}
					defaultValue={searchParams.get("query")?.toString()}
				/>
				<button className="w-10 grid place-content-center" aria-label="Clear input button" type="reset">
					<XMarkIcon className="w-4 h-4 text-white" />
				</button>
			</form>
		</>
	)
}

export default Search

// src/lib/components/search.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { page } from '$app/state';
	import { resolve } from '$app/paths';
	import MagnifyingGlassIcon from './icons/MagnifyingGlassIcon.svelte';
	import XMarkIcon from './icons/XMarkIcon.svelte';

	let pathname: string = $derived(page.url.pathname);
	let search_query = $derived(page.url.searchParams.get('s') || '');
	// let search = $state('');
	function handleSubmit(event: Event) {
		event.preventDefault();
		goto(resolve(`/${pathname}?s=${search_query}` as `/`));
	}
	function handleClear() {
		goto(resolve(`${pathname}` as `/`));
	}
</script>

<form
	onsubmit={handleSubmit}
	class="flex rounded-md border border-zinc-700 bg-zinc-800 text-sm text-white shadow"
>
	<div aria-disabled="true" class="grid w-10 place-content-center">
		<MagnifyingGlassIcon />
	</div>
	<input
		type="text"
		spellCheck="false"
		name="text"
		class="w-20 bg-transparent py-1.5 transition-all outline-none placeholder:text-zinc-400 focus:w-48"
		placeholder="Search..."
		bind:value={search_query}
	/>
	{#if search_query != ''}
		<button
			onclick={handleClear}
			class="grid w-10 place-content-center"
			aria-label="Clear input button"
			type="reset"
		>
			<XMarkIcon />
		</button>
	{/if}
</form>
