// src/routes/(main)/tags/[id]/+page.svelte
<script>
	import ChapterList from '$lib/components/chapter-list.svelte';
	import TagIcon from '$lib/components/icons/TagIcon.svelte';
	import Pagination from '$lib/components/paginations/pagination.svelte';
	import SkeletonKomik from '$lib/components/skeletons/skeleton-komik.svelte';
	const { data } = $props();
</script>

<div class="flex items-center justify-center gap-4">
	<TagIcon />
	<h1 class="text-2xl font-bold">{data.tag.name}</h1>
</div>
<div class="my-8 grid grid-cols-1 gap-4 md:grid-cols-6 md:gap-6">
	{#await data.komik}
		<SkeletonKomik />
	{:then komik}
		{#each komik as item (item.id)}
			<ChapterList data={item} pathName={`/tags/${data.tag.id}`} image_cdn={data.image_cdn} />
		{/each}
	{/await}
</div>
<div class="my-28 flex justify-center">
	<Pagination totalPages={data.totalPage} />
</div>

// src/app/(main)/tags/[id]/page.tsx
import React, { JSX, Suspense } from 'react'
import { getTags } from '@/db/queries/tags';
import { getKomikTaggetSearchPagin, getKomikTagTotalPage } from '@/db/queries/komik';
import ChapterList from "@/components/chapter-list"
import Pagination from "@/components/pagination"
import SkeletonKomik from "@/components/skeleton-komik"
import { FireIcon } from "@heroicons/react/24/solid"
import { CDNType, getCDN } from '@/lib/nhapi';

export const revalidate = 3600;

export const generateMetadata = async ({
  params,
}: {
  params: Promise<{ id: string }>
}) => {
	const { id } = await params
	const data = await getTags(Number(id))
	const title = data.name
	return {
		title: `${title}`,
	}
}

type TagsPageIdProps = {
  params: Promise<{ id: string | number }>;
  searchParams: Promise<{ query?: string; page?: string | number }>;
};

const TagsPageId = async ({ params, searchParams }: TagsPageIdProps): Promise<JSX.Element> => {
	const csp = await searchParams
	const { id } = await params
  const query = csp?.query || ""
  const currentPage = Number(csp?.page) || 1
  const tag = await getTags(Number(id))
  const data = await getKomikTaggetSearchPagin(Number(id), query, currentPage)
  const totalPage = await getKomikTagTotalPage(Number(id), query)
	const image_cdn:CDNType = await getCDN()
  return (
    <>
    <div className="flex justify-center items-center gap-4">
				<FireIcon className="w-6 text-red-500" />
				<h1 className="text-2xl font-bold">{tag.name}</h1>
			</div>
			<div className="my-8 grid grid-cols-1 gap-4 md:grid-cols-6 md:gap-6">
				<Suspense key={query + currentPage} fallback={<SkeletonKomik />}>
					<ChapterList data={data} image_cdn={image_cdn} />
				</Suspense>
			</div>
			<div className="flex justify-center mt-4">
				<Pagination totalPages={totalPage} />
			</div>
    </>
  )
}

export default TagsPageId
